version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend-build
    working_dir: /app/backend
    command: gunicorn -b 0.0.0.0:5000 app:app
    volumes:
      - ./backend/credentials.json:/app/backend/credentials.json:ro
      - ./backend/.env:/app/backend/.env:ro
    environment:
      - PYTHONUNBUFFERED=1
    expose:
      - "5000"
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
